@echo on
dsadd user "CN=Leonicio\, Rivera,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid LXRivera -upn LXRivera@corp.local -pwd !lxr2012lxr -fn "Leonicio" -ln "Rivera" -display "Leonicio Rivera" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Samuel\, Torres,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid SXTorres -upn SXTorres@corp.local -pwd !sxt2012sxt -fn "Samuel" -ln "Torres" -display "Samuel Torres" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Nicholas\, McGuire,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid NXMcguire -upn NXMcguire@corp.local -pwd !nxm2012nxm -fn "Nicholas" -ln "McGuire" -display "Nicholas McGuire" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Muchammad\, Awaais,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid MXAwaais -upn MXAwaais@corp.local -pwd !mxa2012mxa -fn "Muchammad" -ln "Awaais" -display "Muchammad Awaais" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=John\, Pucci,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid JXPucci -upn JXPucci@corp.local -pwd !jxp2012jxp -fn "John" -ln "Pucci" -display "John Pucci" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Dennis\, Tajah,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid DXTajah -upn DXTajah@corp.local -pwd !dxt2012dxt -fn "Dennis" -ln "Tajah" -display "Dennis Tajah" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Luis\, Reyes,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid LXReyes -upn LXReyes@corp.local -pwd !lxr2012lxr -fn "Luis" -ln "Reyes" -display "Luis Reyes" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Sandra\, Delong,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid SXDelong -upn SXDelong@corp.local -pwd !sxd2012sxd -fn "Sandra" -ln "Delong" -display "Sandra Delong" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Jose\, Bermundez,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid JXBermundez -upn JXBermundez@corp.local -pwd !jxb2012jxb -fn "Jose" -ln "Bermundez" -display "Jose Bermundez" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
dsadd user "CN=Raul\, Mendoza,OU=Kablelink,OU=CONTRACTORS,OU=TAMPA BAY,DC=corp,DC=local" -samid RXMendoza -upn RXMendoza@corp.local -pwd !rxm2012rxm -fn "Raul" -ln "Mendoza" -display "Raul Mendoza" -company "Hillsborough Kablelink" -dept "Kablelink Contractor" -pwdneverexpires yes -disabled no
pause