
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-CertificateServices
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-CertificateServices-CA
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-CertificateServices-OnlineResponder
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD-DS
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD-DS-SnapIns
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD-Powershell
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD-DS-AdministrativeCenter
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD-DS-NIS
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-AD-LDS
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-DHCP
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-DNS
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-FileServices
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-FileServices-Dfs
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-FileServices-Fsrm
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-FileServices-StorageMgmt
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-HyperV
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Roles-RDS
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-BitLocker
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-Clustering
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-GP
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-LoadBalancing
dism.exe /online /quiet /enable-feature /featurename:IIS-WebServerRole
dism.exe /online /quiet /enable-feature /featurename:IIS-WebServerManagementTools
dism.exe /online /quiet /enable-feature /featurename:IIS-IIS6ManagementCompatibility
dism.exe /online /quiet /enable-feature /featurename:IIS-Metabase
dism.exe /online /quiet /enable-feature /featurename:IIS-LegacySnapIn
dism.exe /online /quiet /enable-feature /featurename:IIS-WebServerManagementTools
dism.exe /online /quiet /enable-feature /featurename:IIS-WebServerRole
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-SmtpServer
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-StorageExplorer
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-StorageManager
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-Features-Wsrm
dism.exe /online /quiet /enable-feature /featurename:RemoteServerAdministrationTools-ServerManager 